spring:
  application:
    name: armeria-basics
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/${spring.datasource.name}
    username: ${spring.datasource.name}
    password: ${spring.datasource.name}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    user: ${spring.datasource.name}
    password: ${spring.datasource.name}
    url: ${spring.datasource.url}

logging:
  level:
    team.mediasoft.study.reactive.flights: debug