spring:
  application:
    name: armeria-basics
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/${spring.datasource.name}
    username: ${spring.datasource.name}
    password: ${spring.datasource.name}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    user: ${spring.datasource.name}
    password: ${spring.datasource.name}
    url: ${spring.datasource.url}
  r2dbc:
    username: ${spring.datasource.name}
    password: ${spring.datasource.name}
    url: r2dbc:postgresql://localhost:5432/${spring.datasource.name}
    pool:
      enabled: true
      initial-size: 5
      max-idle-time: 1m
      max-size: 10
  data:
    r2dbc.repositories.enabled: true

logging:
  level:
    team.mediasoft.study.reactive.flights: debug